version: "3"
services:
  atm-machine-database:
    image: postgres:latest
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=atmmachinedb
      - POSTGRES_USER=atmmachinedb
      - POSTGRES_PASSWORD=atmmachinedb
