server:
  port: 9016
  servlet:
    context-path: /rest/external
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/atmmachinedb
    username: atmmachinedb
    password: atmmachinedb

management:
  endpoints:
    web:
      exposure:
        include: health,info,heapdump,threaddump,metrics
      path-mapping:
        health: status
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true

external-services:
  bank-service:
    username: test
    password: test
    base-path: http://localhost:28999/bank-service/rest/external
    account-get-path: ${external-services.bank-service.base-path}/accounts/{accountNo}/cards/{cardId}/activate
    check-balance-get-path: ${external-services.bank-service.base-path}/accounts/{accountNo}/checkBalance
    deposit-url-path: ${external-services.bank-service.base-path}/accounts/{accountNo}/deposit
    withdraw-path: ${external-services.bank-service.base-path}/accounts/{accountNo}/withdraw

springdoc:
  swagger-ui:
    path: /api-docs
